version: '3.4'

services:
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  elasticsearch:
    image: nshou/elasticsearch-kibana

  ecommerce.data:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile
    depends_on:
      - rabbitmq
      - elasticsearch

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile
    depends_on:
      - rabbitmq
      - elasticsearch

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity.API/Dockerfile
    depends_on:
      - ecommerce.data
      - rabbitmq
      - elasticsearch

  mvc:
    image: ${DOCKER_REGISTRY-}mvc
    build:
      context: .
      dockerfile: Web Apps/MVC/Dockerfile
    depends_on:
      - rabbitmq
      - ecommerce.data
      - elasticsearch

  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: Web Apps/WebStatus/Dockerfile
